# Generated by Django 5.1.5 on 2025-02-11 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_alter_purchaseorder_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the order was approved', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the order was rejected', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the order', null=True),
        ),
    ]
